spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: credit-service-mcp-server
        version: 0.0.1
  application:
    name: credit-service
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    max-connections: 2000
logging:
  level:
    root: INFO
    com.fintech.aiagent: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO